import math
print("Please enter three integer numbers.")
num1 = int(input("Enter first number: "))
num2 = int(input("Enter second number: "))
num3 = int(input("Enter third number: "))
sumNumber = int(num1 + num2 + num3)
productNumber = int(num1 * num2 * num3)
averageNumber = int((num1 + num2 + num3) / 3)
print(f"sum:{sumNumber}")
print(f"product:{productNumber}")
print(f"average:{averageNumber}")